# Generated by Django 4.0.5 on 2022-07-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=12)),
                ('conference_initial_date', models.CharField(max_length=10)),
                ('conference_end_date', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'conference',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=8)),
                ('event_room', models.CharField(max_length=6)),
                ('event_initial_date', models.CharField(max_length=10)),
                ('event_end_date', models.CharField(max_length=10)),
                ('event_initial_time', models.CharField(max_length=5)),
                ('event_end_time', models.CharField(max_length=5)),
                ('event_speaker', models.CharField(max_length=9)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.conference')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
